/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tarea1;

import javax.swing.DefaultListModel;

/**
 *
 * @author albertocastro
 */
public class Vista1 extends javax.swing.JFrame {

    /**
     * Creates new form Vista1
     */
    DefaultListModel modeloLista = new DefaultListModel();

    public Vista1() {
        initComponents();
        lstMeses.setModel(modeloLista);
        setLocationRelativeTo(null);
        setResizable(false);
        setTitle("BIENVENIDOS");

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        buttonGroup5 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        btnRellenar = new javax.swing.JButton();
        btnVaciar = new javax.swing.JButton();
        optTri1 = new javax.swing.JRadioButton();
        optTri2 = new javax.swing.JRadioButton();
        optTri3 = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        optTri4 = new javax.swing.JRadioButton();
        etiMes = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        lstMeses = new javax.swing.JList<>();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Meses");

        btnRellenar.setText("Rellenar");
        btnRellenar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRellenarActionPerformed(evt);
            }
        });

        btnVaciar.setText("Vaciar");
        btnVaciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVaciarActionPerformed(evt);
            }
        });

        optTri1.setText("Trimestre 1");
        optTri1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                optTri1MouseClicked(evt);
            }
        });
        optTri1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                optTri1ActionPerformed(evt);
            }
        });

        optTri2.setText("Trimestre 2");
        optTri2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                optTri2MouseClicked(evt);
            }
        });
        optTri2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                optTri2ActionPerformed(evt);
            }
        });

        optTri3.setText("Trimestre 3");
        optTri3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                optTri3MouseClicked(evt);
            }
        });
        optTri3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                optTri3ActionPerformed(evt);
            }
        });

        jLabel2.setText("Trimestres");

        optTri4.setText("Trimestre 4");
        optTri4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                optTri4MouseClicked(evt);
            }
        });
        optTri4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                optTri4ActionPerformed(evt);
            }
        });

        etiMes.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jScrollPane2.setViewportView(lstMeses);

        jButton1.setText("Salir");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(btnRellenar)
                                    .addComponent(btnVaciar)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addComponent(jLabel1)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(33, 33, 33)
                                .addComponent(jLabel2))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(optTri4, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(optTri2, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(optTri3, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(optTri1, javax.swing.GroupLayout.Alignment.TRAILING))))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButton1)
                            .addComponent(etiMes, javax.swing.GroupLayout.PREFERRED_SIZE, 408, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnRellenar)
                                .addGap(6, 6, 6)
                                .addComponent(btnVaciar))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(optTri1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(optTri2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(optTri3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(optTri4)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                        .addComponent(jButton1))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2)))
                .addGap(18, 18, 18)
                .addComponent(etiMes, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void optTri1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_optTri1ActionPerformed
        // TODO add your handling code here:
        if (optTri1.isSelected() == true) {
            etiMes.setText("Usted ha seleccionado el trimestre 1");
        }
    }//GEN-LAST:event_optTri1ActionPerformed

    private void optTri2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_optTri2ActionPerformed
        // TODO add your handling code here:
        if (optTri2.isSelected() == true) {
            etiMes.setText("Usted ha seleccionado el trimestre 2");
        }
    }//GEN-LAST:event_optTri2ActionPerformed

    private void optTri3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_optTri3ActionPerformed
        // TODO add your handling code here:
        if (optTri3.isSelected() == true) {
            etiMes.setText("Usted ha seleccionado el trimestre 3");
        }
    }//GEN-LAST:event_optTri3ActionPerformed

    private void optTri4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_optTri4ActionPerformed
        // TODO add your handling code here:
        if (optTri4.isSelected() == true) {
            etiMes.setText("Usted ha seleccionado el trimestre 4");
        }
    }//GEN-LAST:event_optTri4ActionPerformed

    private void btnRellenarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRellenarActionPerformed
        // TODO add your handling code here:
        //optTri1
        if (optTri1.isSelected() == true) {
            //lstMesess.
            modeloLista.addElement("Enero");
            modeloLista.addElement("Febrero");
            modeloLista.addElement("Marzo");
           
        } else {
            if (optTri2.isSelected() == true) {
                modeloLista.addElement("Abril");
                modeloLista.addElement("Mayo");
                modeloLista.addElement("Junio");
               
            } else {
                if (optTri3.isSelected() == true) {
                    modeloLista.addElement("Julio");
                    modeloLista.addElement("Agosto");
                    modeloLista.addElement("Septiembre");
                   
                } else {
                    if (optTri4.isSelected() == true) {
                        modeloLista.addElement("Octubre");
                        modeloLista.addElement("Noviembre");
                        modeloLista.addElement("Diciembre");
                        
                    }
                }
            }
        }
    }//GEN-LAST:event_btnRellenarActionPerformed

    private void optTri1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_optTri1MouseClicked
        // TODO add your handling code here:
        if (optTri1.isSelected() == true) {
            optTri2.setSelected(false);
            optTri3.setSelected(false);
            optTri4.setSelected(false);
        }
    }//GEN-LAST:event_optTri1MouseClicked

    private void optTri2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_optTri2MouseClicked
        // TODO add your handling code here:
        if (optTri2.isSelected() == true) {
            optTri1.setSelected(false);
            optTri3.setSelected(false);
            optTri4.setSelected(false);
        }
    }//GEN-LAST:event_optTri2MouseClicked

    private void btnVaciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVaciarActionPerformed
        // TODO add your handling code here:
       
        etiMes.setText(null);
        optTri1.setSelected(false);
        optTri2.setSelected(false);
        optTri3.setSelected(false);
        optTri4.setSelected(false);
         //lstMesess.setModel(null);
          modeloLista.clear();

    }//GEN-LAST:event_btnVaciarActionPerformed

    private void optTri3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_optTri3MouseClicked
        // TODO add your handling code here:
        if (optTri3.isSelected() == true) {
            optTri1.setSelected(false);
            optTri2.setSelected(false);
            optTri4.setSelected(false);
            
        }
    }//GEN-LAST:event_optTri3MouseClicked

    private void optTri4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_optTri4MouseClicked
        // TODO add your handling code here:
        if (optTri4.isSelected() == true) {
            optTri1.setSelected(false);
            optTri2.setSelected(false);
            optTri3.setSelected(false);
        }
    }//GEN-LAST:event_optTri4MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Vista1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Vista1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Vista1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Vista1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Vista1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRellenar;
    private javax.swing.JButton btnVaciar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.ButtonGroup buttonGroup5;
    private javax.swing.JLabel etiMes;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JList<String> lstMeses;
    private javax.swing.JRadioButton optTri1;
    private javax.swing.JRadioButton optTri2;
    private javax.swing.JRadioButton optTri3;
    private javax.swing.JRadioButton optTri4;
    // End of variables declaration//GEN-END:variables
}
